rootProject.name = "arivon"
include("arivon-common")
include("arivon-sql-parent")
include("arivon-sql-mysql")
include("arivon-sql-mariadb")
include("arivon-sql-h2")
include("arivon-sql-postgresql")
include("arivon-document-parent")
include("arivon-document-redis")
include("arivon-demo")
